---
driver:
  name: vagrant
  synced_folders:
    - ["./test", "/tmp/test"]

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14
  roles_path: 'test/integration/roles'
  data_bags_path: 'test/integration/data_bags'
  environments_path: 'test/integration/environments'
  client_rb:
    environment: 'test_splunk'

verifier:
  sudo: true
  name: inspec
  path: test/integration/smoke/%suite%

platforms:
 - name: centos-7.6

suites:
- name: s_standalone
  driver:
    network:
      - ['private_network', {ip: '33.33.33.20'}]
  run_list:
  - role[s_standalone]
  attributes:
    chef-vault:
      databag_fallback: true
